-- ==========================================
-- STEP 1: INFRASTRUCTURE SETUP
-- Purpose: Create the DB, Schema, and Raw Table
-- ==========================================

-- 1. Set Permissions
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

-- 2. Create Database
CREATE OR REPLACE DATABASE ILLINOIS_INSURANCE_DB;

-- 3. Create Schema
CREATE OR REPLACE SCHEMA ILLINOIS_INSURANCE_DB.RAW;

-- 4. Create Table
CREATE OR REPLACE TABLE ILLINOIS_INSURANCE_DB.RAW.MARKET_SHARE_RAW (
    NAIC_CODE STRING,
    COMPANY_NAME STRING,
    DOMICILE STRING,
    PREMIUMS_WRITTEN STRING,
    MARKET_SHARE STRING,
    PREMIUMS_EARNED STRING,
    LOSSES_INCURRED STRING,
    LOSS_RATIO STRING
);