-- SCHEMA CLEANUP: Removing dbt bootstrap models
DROP TABLE IF EXISTS ILLINOIS_INSURANCE_DB.ANALYTICS.MY_FIRST_DBT_MODEL;
DROP TABLE IF EXISTS ILLINOIS_INSURANCE_DB.ANALYTICS.MY_SECOND_DBT_MODEL;
DROP VIEW IF EXISTS ILLINOIS_INSURANCE_DB.ANALYTICS.MY_SECOND_DBT_MODEL;

-- QUALITY ASSURANCE: Confirming final table structure
SHOW TABLES IN ILLINOIS_INSURANCE_DB.ANALYTICS;

-- DATA PREVIEW: Spot-checking the "Gold" layer for Power BI
SELECT * FROM ILLINOIS_INSURANCE_DB.ANALYTICS.FCT_INSURANCE_MARKET_SHARE 
LIMIT 10;